#! /usr/bin/bash

# bash completion for clatex
# copy this file to /usr/share/bash-completion/completions/clatex:
# $ cp clatex_completion /usr/share/bash-completion/completions/clatex

_clatex()
{
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts="-h --help -f -c -g -q -o -p -v -b -a -j -t --onlytex -z -k --tikz --table --plain --plots --filter -w -e --engine --sl --sd"

  if [[ "$cur" != -* ]]; then
        _filedir '@(tex|py)'
  else
      COMPREPLY=( $( compgen -W "$opts" -- "$cur" ) )
  fi

    return 0
}

complete -F _clatex clatex
